<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/retrieveEmployees" xmlns:tns="myspace.com/hrm"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/retrieveEmployees_table.xsd"/>
        <oracle-xsl-mapper:rootElement name="EmployeesCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/retrieveEmployees"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/HrmService.xsd"/>
        <oracle-xsl-mapper:rootElement name="EmployeeList" namespace="myspace.com/hrm"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI DEC 12 08:34:18 CET 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:EmployeeList>
      <xsl:for-each select="/ns0:EmployeesCollection/ns0:Employees">
        <xsl:if test=".">
          <tns:Employees>
            <tns:FirstName>
              <xsl:value-of select="ns0:firstName"/>
            </tns:FirstName>
            <tns:Surname>
              <xsl:value-of select="ns0:lastName"/>
            </tns:Surname>
            <tns:Salary>
              <xsl:value-of select="ns0:salary"/>
            </tns:Salary>
            <tns:Hiredate>
              <xsl:value-of select="ns0:hireDate"/>
            </tns:Hiredate>
            <tns:Department>
              <xsl:value-of select="ns0:departmentId"/>
            </tns:Department>
            <tns:JobTitle>
              <xsl:value-of select="ns0:jobId"/>
            </tns:JobTitle>
            <tns:EmailAddress>
              <xsl:value-of select="ns0:email"/>
            </tns:EmailAddress>
            <tns:EmployeeNumber>
              <xsl:value-of select="ns0:employeeId"/>
            </tns:EmployeeNumber>
            <tns:ManagerName>
              <xsl:value-of select="ns0:managerId/ns0:lastName"/>
            </tns:ManagerName>
          </tns:Employees>
        </xsl:if>
      </xsl:for-each>
    </tns:EmployeeList>
  </xsl:template>
</xsl:stylesheet>
