<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:tns="http://TargetNamespace.com/HumanCapitalService_getColleagues_response"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="myspace.com/hrm"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/HrmService.xsd"/>
        <oracle-xsl-mapper:rootElement name="EmployeeList" namespace="myspace.com/hrm"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/nxsd_jsonEmployeeList.xsd"/>
        <oracle-xsl-mapper:rootElement name="Employees"
                                       namespace="http://TargetNamespace.com/HumanCapitalService_getColleagues_response"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI DEC 12 11:05:03 CET 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:Employees>
      <xsl:for-each select="/ns0:EmployeeList/ns0:Employees">
        <tns:employees>
          <tns:firstname>
            <xsl:value-of select="ns0:FirstName"/>
          </tns:firstname>
          <tns:lastname>
            <xsl:value-of select="ns0:Surname"/>
          </tns:lastname>
          <tns:function>
            <xsl:value-of select="ns0:JobTitle"/>
          </tns:function>
          <tns:employeeIdentifier>
            <xsl:value-of select="ns0:EmployeeNumber"/>
          </tns:employeeIdentifier>
          <tns:renumeration>
            <xsl:value-of select="ns0:Salary"/>
          </tns:renumeration>
          <tns:division>
            <xsl:value-of select="ns0:Department"/>
          </tns:division>
          <tns:manager>
            <xsl:value-of select="ns0:ManagerName"/>
          </tns:manager>
        </tns:employees>
      </xsl:for-each>
    </tns:Employees>
  </xsl:template>
</xsl:stylesheet>
