<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ldap/LDAPInteractor/LDAPInteractor/ReadLDAPEntry" name="ReadLDAPEntry-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ReadLDAPEntry.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ldap/LDAPInteractor/LDAPInteractor/ReadLDAPEntry"/>
    <wsdl:binding name="search_ptt-binding" type="read:search_ptt" xmlns:read="http://xmlns.oracle.com/pcbpel/adapter/ldap/LDAPInteractor/LDAPInteractor/ReadLDAPEntry">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="search">
            <soap:operation soapAction="search"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>