<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="saibot.airport/services/utility/reference"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:refData="saibot.airport/data/reference" xmlns:common="saibot.airport/data/common">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/RawCountryService.xsd"/>
        <oracle-xsl-mapper:rootElement name="getAllCountriesResponseMessage"
                                       namespace="saibot.airport/services/utility/reference"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/CountryService.xsd"/>
        <oracle-xsl-mapper:rootElement name="findCountriesResponseMessage"
                                       namespace="saibot.airport/services/utility/reference"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON AUG 11 18:03:09 CEST 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="countryCode"/>
  <xsl:param name="countryName"/>
  <xsl:param name="continent"/>
  <xsl:template match="/">
    <ns0:findCountriesResponseMessage>
      <ns0:Countries>
        <xsl:for-each select="/ns0:getAllCountriesResponseMessage/ns0:Countries/ns0:Country[(($countryName= '*') or starts-with(refData:name,$countryName)) and (($countryCode= '*') or starts-with(refData:code,$countryCode)) and (($continent= '*') or ($continent= '') or refData:continent=$continent)]">
          <ns0:Country>
            <refData:code>
              <xsl:value-of select="refData:code"/>
            </refData:code>
            <refData:name>
              <xsl:value-of select="refData:name"/>
            </refData:name>
            <refData:continent>
              <xsl:value-of select="refData:continent"/>
            </refData:continent>
            <refData:wikipediaReference>
              <xsl:value-of select="refData:wikipediaReference"/>
            </refData:wikipediaReference>
          </ns0:Country>
        </xsl:for-each>
      </ns0:Countries>
    </ns0:findCountriesResponseMessage>
  </xsl:template>
</xsl:stylesheet>
