<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="HelloWorld"
     targetNamespace="http://xmlns.oracle.com/SimpleHelloWorldWithEDNPublish/SimpleHelloWorldWithEDNPublish/HelloWorld"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/SimpleHelloWorldWithEDNPublish/SimpleHelloWorldWithEDNPublish/HelloWorld"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="my.org/pr"
    >
    <plnk:partnerLinkType name="HelloWorld">
        <plnk:role name="HelloWorldProvider" portType="client:HelloWorld"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/SimpleHelloWorldWithEDNPublish/SimpleHelloWorldWithEDNPublish/HelloWorld"
                 schemaLocation="../Schemas/HelloWorld.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="my.org/pr" schemaLocation="../Schemas/HelloEvents.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="HelloWorldRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="HelloWorldResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="HelloWorld">
        <wsdl:operation name="process">
            <wsdl:input message="client:HelloWorldRequestMessage"/>
            <wsdl:output message="client:HelloWorldResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
