<wsdl:definitions
     name="InterceptUpdatedLDAPEntries"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ldap/LDAPInteractorSOAComposite/LDAPInteractorSOAComposite/InterceptUpdatedLDAPEntries"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ldap/LDAPInteractorSOAComposite/LDAPInteractorSOAComposite/InterceptUpdatedLDAPEntries"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://platform.integration.oracle/blocks/adapter/fw/metadata/InterceptUpdatedLDAPEntries"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="entryChangeNotification_plt" >
    <plt:role name="entryChangeNotification_role" >
      <plt:portType name="tns:entryChangeNotification_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://platform.integration.oracle/blocks/adapter/fw/metadata/InterceptUpdatedLDAPEntries" schemaLocation="../Schemas/InterceptUpdatedLDAPEntries.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="entryChangeNotification_response_msg">
        <wsdl:part name="body" element="imp1:entryChangeNotificationResponse"/>
    </wsdl:message>
    <wsdl:portType name="entryChangeNotification_ptt">
        <wsdl:operation name="entryChangeNotification">
            <wsdl:input message="tns:entryChangeNotification_response_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
