<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://TargetNamespace.com/IMDBRestAPI_Operation1_response"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="MovieSearcher"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="nxsd_imbdMovieResponse.xsd"/>
        <oracle-xsl-mapper:rootElement name="Movie"
                                       namespace="http://TargetNamespace.com/IMDBRestAPI_Operation1_response"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="Movie.xsd"/>
        <oracle-xsl-mapper:rootElement name="Movie" namespace="MovieSearcher"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI DEC 12 13:54:09 CET 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:Movie>
      <tns:title>
        <xsl:value-of select="/ns0:Movie/ns0:data/ns0:title"/>
      </tns:title>
      <tns:year>
        <xsl:value-of select="/ns0:Movie/ns0:data/ns0:year"/>
      </tns:year>
      <tns:rating>
        <xsl:value-of select="/ns0:Movie/ns0:data/ns0:rating"/>
      </tns:rating>
      <tns:description>
        <xsl:value-of select="/ns0:Movie/ns0:data/ns0:description"/>
      </tns:description>
      <tns:cast>
        <xsl:for-each select="/ns0:Movie/ns0:data/ns0:cast">
          <tns:actor>
            <xsl:value-of select="."/>
          </tns:actor>
        </xsl:for-each>
      </tns:cast>
      <tns:releaseDate>
        <xsl:value-of select="/ns0:Movie/ns0:data/ns0:releaseDate"/>
      </tns:releaseDate>
      <tns:directors>
        <xsl:value-of select="/ns0:Movie/ns0:data/ns0:directors"/>
      </tns:directors>
      <tns:writers>
        <xsl:for-each select="/ns0:Movie/ns0:data/ns0:writers">
          <tns:person>
            <xsl:value-of select="."/>
          </tns:person>
        </xsl:for-each>
      </tns:writers>
      <tns:genres>
        <xsl:for-each select="/ns0:Movie/ns0:data/ns0:genres">
          <tns:label>
            <xsl:value-of select="."/>
          </tns:label>
        </xsl:for-each>
      </tns:genres>
      <tns:poster/>
      <tns:runningTime>
        <xsl:value-of select="/ns0:Movie/ns0:data/ns0:runningTime"/>
      </tns:runningTime>
    </tns:Movie>
  </xsl:template>
</xsl:stylesheet>
