//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140310.1920 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.17 at 09:50:42 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "my.org/pr", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.my.pr;
