<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://xmlns.amis.nl/edesk/frm/0200"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns4="http://xmlns.amis.nl/edesk/common"
                xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:ns3="http://schemas.oracle.com/service/bpel/common"
                xmlns:tns="http://xmlns.amis.nl/edesk/webformservice"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.oracle.com/bpel/extension">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/webformServiceWrapper.wsdl"/>
        <oracle-xsl-mapper:rootElement name="FormAnswer" namespace="http://xmlns.amis.nl/edesk/frm/0200"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/WebFormEOL/WSDL/webformService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="FormAnswer" namespace="http://xmlns.amis.nl/edesk/frm/0200"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:named-template-schema>
      <oracle-xsl-mapper:template name="sayHello">
        <oracle-xsl-mapper:mapSources/>
      </oracle-xsl-mapper:template>
    </oracle-xsl-mapper:named-template-schema>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED DEC 17 14:38:42 CET 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:FormAnswer>
      <ns4:messageDetails>
        <ns4:messageType>
          <xsl:value-of select="/ns0:FormAnswer/ns4:messageDetails/ns4:messageType"/>
        </ns4:messageType>
        <xsl:apply-templates select="/ns0:FormAnswer/ns4:messageDetails/ns4:owner"/>
        <ns4:sendDate>
          <xsl:value-of select="/ns0:FormAnswer/ns4:messageDetails/ns4:sendDate"/>
        </ns4:sendDate>
        <ns4:sender>
          <ns4:organisation>
            <xsl:value-of select="/ns0:FormAnswer/ns4:messageDetails/ns4:sender/ns4:organisation"/>
          </ns4:organisation>
          <ns4:application>
            <xsl:value-of select="/ns0:FormAnswer/ns4:messageDetails/ns4:sender/ns4:application"/>
          </ns4:application>
          <xsl:if test="/ns0:FormAnswer/ns4:messageDetails/ns4:sender/ns4:user">
            <ns4:user>
              <xsl:value-of select="/ns0:FormAnswer/ns4:messageDetails/ns4:sender/ns4:user"/>
            </ns4:user>
          </xsl:if>
          <xsl:if test="/ns0:FormAnswer/ns4:messageDetails/ns4:sender/ns4:action">
            <ns4:action>
              <xsl:value-of select="/ns0:FormAnswer/ns4:messageDetails/ns4:sender/ns4:action"/>
            </ns4:action>
          </xsl:if>
        </ns4:sender>
      </ns4:messageDetails>
      <xsl:if test="/ns0:FormAnswer/ns0:answer">
        <ns0:answer>
          <xsl:for-each select="/ns0:FormAnswer/ns0:answer/ns0:object">
            <ns0:object>
              <ns0:processId>
                <xsl:value-of select="ns0:processId"/>
              </ns0:processId>
              <ns0:intakeId>
                <xsl:value-of select="ns0:intakeId"/>
              </ns0:intakeId>
              <xsl:if test="ns0:caseId">
                <ns0:caseId>
                  <xsl:value-of select="ns0:caseId"/>
                </ns0:caseId>
              </xsl:if>
              <xsl:if test="ns0:properties">
                <ns0:properties>
                  <xsl:for-each select="ns0:properties/ns0:item">
                    <ns0:item>
                      <ns0:itemname>
                        <xsl:value-of select="ns0:itemname"/>
                      </ns0:itemname>
                      <xsl:if test="ns0:itemtype">
                        <ns0:itemtype>
                          <xsl:value-of select="ns0:itemtype"/>
                        </ns0:itemtype>
                      </xsl:if>
                      <ns0:itemvalue>
                        <xsl:if test="ns0:itemvalue/@xsi:nil">
                          <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                            <xsl:value-of select="ns0:itemvalue/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:itemvalue"/>
                      </ns0:itemvalue>
                    </ns0:item>
                  </xsl:for-each>
                </ns0:properties>
              </xsl:if>
              <ns0:statusDetails>
                <ns0:statusCode>
                  <xsl:value-of select="ns0:statusDetails/ns0:statusCode"/>
                </ns0:statusCode>
                <ns0:statusMessage>
                  <xsl:value-of select="ns0:statusDetails/ns0:statusMessage"/>
                </ns0:statusMessage>
              </ns0:statusDetails>
            </ns0:object>
          </xsl:for-each>
        </ns0:answer>
      </xsl:if>
    </ns0:FormAnswer>
  </xsl:template>
  <xsl:template match="/ns0:FormAnswer/ns4:messageDetails/ns4:owner">
    <ns4:owner>
      <xsl:value-of select='concat ("Hello again ", . )'/>
    </ns4:owner>
  </xsl:template>
</xsl:stylesheet>
