-- USER SQL
ALTER USER "casemgmt" IDENTIFIED BY casemgmt 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "casemgmt" QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO "casemgmt" ;
GRANT "CONNECT" TO "casemgmt" ;

-- SYSTEM PRIVILEGES
GRANT UNLIMITED TABLESPACE TO "casemgmt" ;

