CREATE SEQUENCE CASE_SEQ;

CREATE TABLE CASE 
(
  "ID" NUMBER                NOT NULL
, CASE_REF VARCHAR2(50 CHAR) NOT NULL
, CASE_TYPE VARCHAR2(5 CHAR) NOT NULL
, CASE_VERSION NUMBER        NULL
, CASE_XML CLOB              NULL
, INTAKE_ID NUMBER           NOT NULL 
, INTAKE_DATE TIMESTAMP      NOT NULL
, HAS_DOCS VARCHAR2(1 CHAR)  DEFAULT 'N' NOT NULL 
, CONSTRAINT CASE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN CASE.ID IS 'Case Id';

COMMENT ON COLUMN CASE.CASE_REF IS 'Case Reference (GUID)';

COMMENT ON COLUMN CASE.CASE_TYPE IS 'Case Type Reference';

COMMENT ON COLUMN CASE.CASE_VERSION IS 'Version of used Case Type';

COMMENT ON COLUMN CASE.CASE_XML IS 'Case Data';

COMMENT ON COLUMN CASE.INTAKE_ID IS 'Intake Id';

COMMENT ON COLUMN CASE.INTAKE_DATE IS 'Intake Creation Date';

COMMENT ON COLUMN CASE.HAS_DOCS IS 'Check if case has documents';

ALTER TABLE CASE
ADD CONSTRAINT CASE_CHK_DOCS
  CHECK (HAS_DOCS IN ('Y', 'N'));

CREATE TRIGGER CASE_TRG 
BEFORE INSERT ON CASE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CASE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/